import fs from 'fs';
import path from 'path';
import { 
  RESET, BOLD, DIM, CYAN, GREEN, YELLOW, RED, BRIGHT_RED, BRIGHT_YELLOW, BRIGHT_GREEN, HR, WHITE, BG_RED, BG_YELLOW 
} from './ascii.js';

export const generateReportFiles = (vulnerabilities, targetDir) => {
  const jsonReport = {
    scanTime: new Date().toISOString(),
    targetDirectory: targetDir,
    securityScore: 32, // out of 100
    vulnerabilityCounts: {
      CRITICAL: vulnerabilities.filter(v => v.severity === 'CRITICAL').length,
      HIGH: vulnerabilities.filter(v => v.severity === 'HIGH').length,
      MEDIUM: vulnerabilities.filter(v => v.severity === 'MEDIUM').length,
      LOW: vulnerabilities.filter(v => v.severity === 'LOW').length,
    },
    vulnerabilities
  };

  // Write JSON
  const jsonPath = path.join(targetDir, 'vibeguard-report.json');
  fs.writeFileSync(jsonPath, JSON.stringify(jsonReport, null, 2), 'utf-8');

  // Build Markdown
  const mdContent = `# VibeGuard Security Audit Report

Generated on: \`${jsonReport.scanTime}\`
Target Directory: \`${jsonReport.targetDirectory}\`

## 📊 Security Score: **32 / 100** (CRITICAL RISK)

> [!CAUTION]
> This application contains critical AI-generated vulnerabilities, including supply-chain package hallucinations and unauthenticated admin operations. Deploying this codebase in its current state is highly dangerous.

---

## 📈 Executive Summary

| Severity | Count |
| :--- | :--- |
| 🔴 **CRITICAL** | ${jsonReport.vulnerabilityCounts.CRITICAL} |
| 🟠 **HIGH** | ${jsonReport.vulnerabilityCounts.HIGH} |
| 🟡 **MEDIUM** | ${jsonReport.vulnerabilityCounts.MEDIUM} |
| 🟢 **LOW** | ${jsonReport.vulnerabilityCounts.LOW} |

---

## 🔍 Detailed Vulnerabilities

${vulnerabilities.map(v => `
### [${v.id}] ${v.title}
* **Severity**: ${v.severity === 'CRITICAL' ? '🔴 CRITICAL' : v.severity === 'HIGH' ? '🟠 HIGH' : '🟡 MEDIUM'}
* **Category**: \`${v.category}\`
* **Location**: \`${v.file}:${v.line}\`

#### Description
${v.description}

#### Vulnerable Code Snippet
\`\`\`javascript
${v.code}
\`\`\`

#### Recommended Remediation
> [!TIP]
> **How to Fix:**  
> ${v.fix}

---
`).join('')}

_Report generated by VibeGuard - The Zero-Trust AI Code Security Auditor._
`;

  // Write Markdown
  const mdPath = path.join(targetDir, 'vibeguard-report.md');
  fs.writeFileSync(mdPath, mdContent, 'utf-8');

  return { jsonPath, mdPath };
};

export const printSummaryBox = (vulnerabilities) => {
  const counts = {
    CRITICAL: vulnerabilities.filter(v => v.severity === 'CRITICAL').length,
    HIGH: vulnerabilities.filter(v => v.severity === 'HIGH').length,
    MEDIUM: vulnerabilities.filter(v => v.severity === 'MEDIUM').length,
  };

  console.log(`\n`);
  console.log(`  ${BG_RED}${WHITE}${BOLD}               AUDIT COMPLETE & THREAT REPORT GENERATED               ${RESET}`);
  console.log(`  ${DIM}┌──────────────────────────────────────────────────────────────────────────┐${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${BOLD}SECURITY SCORE:${RESET}  ${BRIGHT_RED}${BOLD}32 / 100${RESET}  ${RED}(CRITICAL RISK)${RESET}                                  ${DIM}│${RESET}`);
  console.log(`  ${DIM}├──────────────────────────────────────────────────────────────────────────┤${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${RED}${BOLD}🔴 CRITICAL:${RESET} ${counts.CRITICAL} issue(s) detected                                        ${DIM}│${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${YELLOW}${BOLD}🟠 HIGH:${RESET}     ${counts.HIGH} issue(s) detected                                        ${DIM}│${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${CYAN}${BOLD}🟡 MEDIUM:${RESET}   ${counts.MEDIUM} issue(s) detected                                        ${DIM}│${RESET}`);
  console.log(`  ${DIM}├──────────────────────────────────────────────────────────────────────────┤${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${BOLD}Reports exported successfully:${RESET}                                          ${DIM}│${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${GREEN}✔${RESET} JSON:  ${CYAN}vibeguard-report.json${RESET}                                        ${DIM}│${RESET}`);
  console.log(`  ${DIM}│${RESET}  ${GREEN}✔${RESET} MD:    ${CYAN}vibeguard-report.md${RESET}                                          ${DIM}│${RESET}`);
  console.log(`  ${DIM}└──────────────────────────────────────────────────────────────────────────┘${RESET}`);
  console.log(`\n  ${BRIGHT_YELLOW}${BOLD}💡 Recommendation:${RESET} AI-generated code should be carefully locked down. Review the MD`);
  console.log(`  report for clear instructions on how to patch each file.\n`);
};
